education:
  project:
    per_page: 16
    truncate: 100
  technique:
    per_page: 6
    truncate: 100
  index:
    max_learning_program_desc: 150
    max_learning_program_name: 20
    max_learning_program: 3
  trainings:
    per_page: 5
    limit_string: 200
  page_404_url: "public/404"
  related_project:
    limit: 20
  projects:
    textarea_rows: 8
    split_array: 4
    min_array_size: 3
  mess_success: "success"
  mess_notice: "notice"
  feedback_form_rows: 6
  feedback_form_cols: 30
  feedback:
    max_name_length: 50
    max_email_length: 255
    max_phone_number_length: 255
    max_subject_length: 255
    min_subject_length: 3
    min_content_length: 10
    max_content_length: 255
  category:
    max_length_title: 200
  posts:
    max_length_title: 200
    content_character_display: 255
    per_page: 20
home:
  limit: 8
home_trainings_limit: 8
company:
  country: ["United States", "Japan", "Germany", "Korea"]
  max_length_name: 50
default_user_password: {"password": "123456"}
courses:
  home_limit: 4
  index_limit: 6
user:
  max_length_name: 50
max_length_title: 50
